-- Valaskjalf/memory schema — PostgreSQL (Munnin's deployed backend).
--
-- The Postgres twin of `migrations/0001_init.sql` + `0002_shared_record_ras.sql`, written
-- at the final shape rather than replaying SQLite's history: Postgres can ALTER a CHECK and
-- add a foreign key in place, so the table-rebuild migration SQLite needed has no
-- counterpart here, and 'ras' is simply part of the CHECK from the first day.
--
-- Dates are TEXT (ISO-8601), matching the entity mapping and the migrated rows exactly,
-- not timestamptz. The application reads and writes ISO strings; keeping the column type
-- identical removes a conversion from the port instead of adding one.
--
-- Full text is a generated `tsvector` column with a GIN index rather than an FTS5
-- external-content table. A stored generated column recomputes on every INSERT/UPDATE, so
-- the three sync triggers the SQLite schema needs have no counterpart either. The 'simple'
-- dictionary is deliberate: FTS5 tokenises without stemming, and `english` would silently
-- change which records a search returns.
--
-- The text is first flattened by `regexp_replace(..., '[^[:alnum:]]+', ' ', 'g')` because
-- Postgres's default parser keeps hyphenated words whole (`shared-memory` is one token)
-- while FTS5's unicode61 tokeniser splits on `-`, so without this a search for `memory`
-- finds every `agent-memory` / `shared-memory` record in FTS5 and none in Postgres. The
-- normalisation reproduces FTS5's "letters and digits are tokens, everything else is a
-- separator" rule. Measured on the live snapshot: this closes the recall gap for every
-- query in the fixture (0 missing, from 100).

-- The tenant. `user_id` is ours forever and is never an issuer's subject; the column keeps
-- its name because three tables below already use it.
CREATE TABLE IF NOT EXISTS account (
  user_id      TEXT PRIMARY KEY,
  display_name TEXT,
  email        TEXT,
  created_date TEXT NOT NULL
);

-- Issuer-to-tenant mapping, keyed on the pair OpenID Connect guarantees to be stable.
CREATE TABLE IF NOT EXISTS user_identity (
  iss         TEXT NOT NULL,
  sub         TEXT NOT NULL,
  user_id     TEXT NOT NULL,
  linked_date TEXT NOT NULL,
  PRIMARY KEY (iss, sub),
  FOREIGN KEY (user_id) REFERENCES account(user_id)
);

-- The agent entity. No lifecycle columns: nothing in the system retires an agent.
CREATE TABLE IF NOT EXISTS agent (
  user_id      TEXT NOT NULL,
  agent_id     TEXT NOT NULL,
  name         TEXT,
  role         TEXT,
  uuid         TEXT,
  created_date TEXT NOT NULL,
  PRIMARY KEY (user_id, agent_id),
  FOREIGN KEY (user_id) REFERENCES account(user_id)
);

-- Fleet-shared memory, owned by no agent. The CHECK admits reasoning, knowledge, the
-- universal RAS triggers, and the user profile; an episode, identity or emotional moment
-- belongs to some particular agent and is refused here.
CREATE TABLE IF NOT EXISTS shared_record (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid          TEXT    NOT NULL UNIQUE,
  user_id       TEXT    NOT NULL,
  record_type   TEXT    NOT NULL CHECK (record_type IN ('reasoning','knowledge','ras','user_profile')),
  project       TEXT,
  title         TEXT,
  tags          TEXT,
  created_date  TEXT    NOT NULL,
  modified_date TEXT    NOT NULL,
  archived_date TEXT,
  deleted_date  TEXT,
  full_content  TEXT,
  search_tsv    tsvector GENERATED ALWAYS AS (
    to_tsvector('simple', regexp_replace(
      coalesce(full_content,'') || ' ' || coalesce(title,'') || ' ' || coalesce(tags,''),
      '[^[:alnum:]]+', ' ', 'g'))
  ) STORED
);

-- Agent-scoped memory = shared_record + agent_id. The composite foreign key means a memory
-- item can never name an owner that does not exist, and cannot reach across tenants.
CREATE TABLE IF NOT EXISTS memory_record (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid          TEXT    NOT NULL UNIQUE,
  user_id       TEXT    NOT NULL,
  agent_id      TEXT    NOT NULL,
  record_type   TEXT    NOT NULL,
  project       TEXT,
  title         TEXT,
  tags          TEXT,
  created_date  TEXT    NOT NULL,
  modified_date TEXT    NOT NULL,
  archived_date TEXT,
  deleted_date  TEXT,
  full_content  TEXT,
  FOREIGN KEY (user_id, agent_id) REFERENCES agent(user_id, agent_id),
  search_tsv    tsvector GENERATED ALWAYS AS (
    to_tsvector('simple', regexp_replace(
      coalesce(full_content,'') || ' ' || coalesce(title,'') || ' ' || coalesce(tags,''),
      '[^[:alnum:]]+', ' ', 'g'))
  ) STORED
);

-- Browse/metadata indexes (the awakening + load reads).
CREATE INDEX IF NOT EXISTS idx_memory_browse
  ON memory_record (user_id, agent_id, record_type, project, created_date);
CREATE INDEX IF NOT EXISTS idx_shared_browse
  ON shared_record (user_id, record_type, project, created_date);

-- Exactly one user profile per tenant. `awaken` answers "has anyone been asked yet" with
-- the presence of a row, so a second profile would satisfy that question with whichever
-- row came first and leave the other invisible.
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_user_profile_per_tenant
  ON shared_record (user_id)
  WHERE record_type = 'user_profile' AND deleted_date IS NULL;

-- Full-text indexes (generated column + GIN) — one per memory table.
CREATE INDEX IF NOT EXISTS idx_memory_search ON memory_record USING GIN (search_tsv);
CREATE INDEX IF NOT EXISTS idx_shared_search ON shared_record USING GIN (search_tsv);
